//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public virtual List<Customer> CustomerItems { get; set; }
        public Customer()
        {
            this.CustomerItems = new List<Customer>();
        }
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Vehicle { get; set; }
        public string VehiclePlate { get; set; }
    }
}
